### ISSUE TITLE
Amlogic S805 device with 3.10.99 kernel

### ISSUE THREAD

**Issue by sivanoff** [lwfinger/rtl8723bs_bt#10]
Hi,

'dmesg|grep tty' outputs nothing on my device. Do I need some options turned on in kernel or this is because I need at least 3.12?

WiFi works with 8723bs module from amlogic kernel, but no bluetooth controller visible in bluetoothctl.

**Comment by sammaz420** [comment]
Same issue here.  Can you make this work on kernel 3.10.99?

**Comment by sivanoff** [comment]
https://github.com/kszaq/linux/commit/8696206ae5d97c1263b1d2ede595a0d629019742 this patch adds h5 support
