### ISSUE TITLE
Location of firmware file?

### ISSUE THREAD

**Issue by Laszlo-Fiat** [lwfinger/rtl8723bs_bt#3]
Bluetooth works nicely on my Teclast X80h with kernel 4.1.4 and your driver.

One small issue:

Makefile puts the firmware to: /lib/firmware/rtl_bt
start_bt.sh puts the firmware to: /lib/firmware/rtlbt/

I don't know which is correct, where rtk_hciattach picks up the firmware from.

Thank you for your work!

**Comment by lwfinger** [comment]
The code says /lib/firmware/rtl_bt/. All are now consistent. Thanks.

**Comment by Laszlo-Fiat** [comment]
This one was fixed.

Thank you.
